# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hannibal Urban Empire
email: okello94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  To reclaim our DNA, our lifestyle, our culture that's been ripped
  from our brothers and sisters, a new empire must rise.
  LOL I play too much... Much love fam.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hannibalurbanempire.com" # the base hostname & protocol for your site
twitter_username: okelloggs
github_username:  okelloggs

# Build settings
markdown: kramdown
